using System.ComponentModel.DataAnnotations;

namespace MyApp.DAL.Entity.DTO
{
    public class UserDTO
    {
        // User ID, typically auto-generated by the database
        public int Id { get; set; }

        // Name property for the user, required and can't be empty
        [Required(ErrorMessage = "Name is required.")]
        [StringLength(100, ErrorMessage = "Name can't be longer than 100 characters.")]
        public string Name { get; set; }

        // Password property for the user, required and has a minimum length
        [Required(ErrorMessage = "Password is required.")]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Password must be at least 6 characters long.")]
        public string Password { get; set; }

        // IsActive flag, optional, can be null
        public bool? IsActive { get; set; }

        // Conversion methods (optional) to map between UserDTO and User
        public static User ToEntity(UserDTO userDTO)
        {
            return new User
            {
                Id = userDTO.Id,
                Name = userDTO.Name,
                Password = userDTO.Password,
                IsActive = userDTO.IsActive
            };
        }

        public static UserDTO FromEntity(User user)
        {
            return new UserDTO
            {
                Id = user.Id,
                Name = user.Name,
                Password = user.Password,
                IsActive = user.IsActive
            };
        }
    }
}
